### ISSUE TITLE
any plan to merge into mmdetection?

### ISSUE THREAD

**Issue by MeepoAII** [Gus-Guo/AugFPN#10]
or  I will try to merge your code into mmdetection

**Comment by Gus-Guo** [comment]
It is welcomed for you to do this.

**Comment by StevenHD** [comment]
Hi MeepoAll, Do U merge AugFPN into mmdetecion? I wanna ask some questions.

**Comment by Xuying2000** [comment]
Hello, have you succeeded? I'd like to ask you a few questions. Thank you
