### ISSUE TITLE
Could you please give me details about this picture ?

### ISSUE THREAD

**Issue by shaohailin** [Gus-Guo/AugFPN#4]
I read this part of the paper many times, but I couldn't understand what you want to say. what is the ratio? why four figures both have 0,1,2,3 in the horizontal axis? Looking forward to your reply!
![图片](https://user-images.githubusercontent.com/56865153/83321003-2eec3600-a27f-11ea-8e18-a22a1c5abfdb.png)
 @Gus-Guo

**Comment by Gus-Guo** [comment]
Each RoI can obtain four weight maps that correspond to each feature level. For each RoI, the ratio for each feature level is the average of the corresponding weight map. Therefore, there are four ratios for each RoI. Each sub figure in Figure 4 represents the average ratio of each feature levels for all RoIs that are assigned to one feature level based on the strategy.

**Comment by shaohailin** [comment]
Thanks for your reply! But I can't truly understand what you said, I feel so sad! Could you please describe one of the four sub-figures in detail?  I think this way will help me understand your wonderful work.
For example，
![图片](https://user-images.githubusercontent.com/56865153/83345960-06317280-a34b-11ea-9944-ec707e224f85.png)
1.Why in level0 sub-figure, blue is higher than others obvious? What can we learn from this phenomenon?
2. In all 4 sub-figures, orange is lower than others. Why and what we can find from the result?
3. Red is highest in later 3 pictures, what can we learn from this phenomenon?

In Chinese：
1. 为什么子图level0中蓝色的比率最高，这个现象对我有什么启示？
2. 在4张子图中，橘色一致比率非常低，为什么会出现这种现象？作者有没有改进方法？
3. 后3张图红色的比率都非常高，这有什么含义/意义？
最后再次感谢作者前面的回答，对于我未能理解您的答复，我感到十分抱歉，希望作者能对我的困惑详细解答，感谢！！！ @Gus-Guo

**Comment by Gus-Guo** [comment]
Sorry for the delay...
1. Sub-figure 1 shows that RoIs that owns smaller scales may need more information from the feature map with big resolution, which contains more detail information.
2. In my opinion, L0 has already owned enough detail information and therefore L1 is not that necessary.
3. In my opinion, large RoIs need more features with large receptive field than smaller RoIs.

**Comment by mary-0830** [comment]
您好，请问level0-level3对应的是P2-P5的RoI吗？
比如说，level3中的3比较高，是不是意味着在level3中P5的权重越高呢？

**Comment by mary-0830** [comment]
还有一个问题，论文中Figure3.(b)的是不是对应着（a）中的虚线框呢？难道(b)仅仅是用于表示实验中ACF吗？

**Comment by Gus-Guo** [comment]
> 您好，请问level0-level3对应的是P2-P5的RoI吗？
> 比如说，level3中的3比较高，是不是意味着在level3中P5的权重越高呢？

是的

**Comment by Gus-Guo** [comment]
> 还有一个问题，论文中Figure3.(b)的是不是对应着（a）中的虚线框呢？难道(b)仅仅是用于表示实验中ACF吗？

Fig. 3 (a) 和(b)是两种独立的模块，(a)是从spatial的维度进行融合；(b)是从channel的维度融合。对于soft roi selection，我们通过实验结果最终选用(a)。

**Comment by mary-0830** [comment]
您好，我还有几个问题想要请教您。
1. 软RoI选择中的ASF过程是不是和Residual Feature Augmentation中的是一样的呢？
2. 怎么根据图4选择最佳的RoI呢？
我这样理解您看对不对。文中您说得是最初RoI是分配给P2，即RoI从P2获取的语义信息最多，然后还需要P5层的信息才能得到选择出最终的RoI。最初P3-P5的RoI信息可以从level0看出，从中获得语义信息比较少，提取出level0中P2的外观信息就可以提升level1中P3、level2中P4、level3中P5的语义信息了。
3. 最后，该怎么使用权重图计算出最终的RoI呢？

请您指点一下，感谢您的回复。谢谢！

**Comment by Gus-Guo** [comment]
> 您好，我还有几个问题想要请教您。
> 
> 1. 软RoI选择中的ASF过程是不是和Residual Feature Augmentation中的是一样的呢？
> 2. 怎么根据图4选择最佳的RoI呢？
>    我这样理解您看对不对。文中您说得是最初RoI是分配给P2，即RoI从P2获取的语义信息最多，然后还需要P5层的信息才能得到选择出最终的RoI。最初P3-P5的RoI信息可以从level0看出，从中获得语义信息比较少，提取出level0中P2的外观信息就可以提升level1中P3、level2中P4、level3中P5的语义信息了。
> 3. 最后，该怎么使用权重图计算出最终的RoI呢？
> 
> 请您指点一下，感谢您的回复。谢谢！

您好。
1. 融合过程是一致的。实验结果表明ASF采用跟Residual Feature Augmentation一致的融合方式有较好的效果。
2. 其实只是去学习怎么提取更好的RoI特征这么一个过程，没有去具体说选择RoI。根据每个level的特征的特性去决定具体哪个level的特征要占更多的比例。
3.每个RoI会产生对应4个level的权重图，每个权重图分别与对应level的特征进行相乘，最后将这4个特征相加融合。
