### ISSUE TITLE
NoneType' object has no attribute 'rcnn'

### ISSUE THREAD

**Issue by Superfly12138** [Gus-Guo/AugFPN#6]
When i test the trained module.i input this conmmad
```
python tools/test.py configs/faster_rcnn_r50_augfpn_1x.py epoch_8.pth --gpus 4 --out results.pkl --eval bbox
```
but it occured an error:
NoneType' object has no attribute 'rcnn'

deteil:
```
File "tools/test.py", line 127, in <module>
    main()
  File "tools/test.py", line 78, in main
    cfg.model, train_cfg=None, test_cfg=cfg.test_cfg)
  File "/home/superfly/AugFPN-master/mmdet/models/builder.py", line 51, in build_detector
    return build(cfg, DETECTORS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/home/superfly/AugFPN-master/mmdet/models/builder.py", line 31, in build
    return _build_module(cfg, registry, default_args)
  File "/home/superfly/AugFPN-master/mmdet/models/builder.py", line 23, in _build_module
    return obj_type(**args)
  File "/home/superfly/AugFPN-master/mmdet/models/detectors/faster_rcnn.py", line 25, in __init__
    pretrained=pretrained)
  File "/home/superfly/AugFPN-master/mmdet/models/detectors/two_stage.py", line 44, in __init__
    if 'use_consistent_supervision' in self.train_cfg.rcnn:
AttributeError: 'NoneType' object has no attribute 'rcnn'

```

**Comment by xiaoshuyun** [comment]
> 当我测试训练有素的模块时，我输入此命令
> 
> ```
> python tools/test.py configs/faster_rcnn_r50_augfpn_1x.py epoch_8.pth --gpus 4 --out results.pkl --eval bbox
> ```
> 
> 但发生错误：
> NoneType'对象没有属性'rcnn'
> 
> 细节：
> 
> ```
> File "tools/test.py", line 127, in <module>
>     main()
>   File "tools/test.py", line 78, in main
>     cfg.model, train_cfg=None, test_cfg=cfg.test_cfg)
>   File "/home/superfly/AugFPN-master/mmdet/models/builder.py", line 51, in build_detector
>     return build(cfg, DETECTORS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
>   File "/home/superfly/AugFPN-master/mmdet/models/builder.py", line 31, in build
>     return _build_module(cfg, registry, default_args)
>   File "/home/superfly/AugFPN-master/mmdet/models/builder.py", line 23, in _build_module
>     return obj_type(**args)
>   File "/home/superfly/AugFPN-master/mmdet/models/detectors/faster_rcnn.py", line 25, in __init__
>     pretrained=pretrained)
>   File "/home/superfly/AugFPN-master/mmdet/models/detectors/two_stage.py", line 44, in __init__
>     if 'use_consistent_supervision' in self.train_cfg.rcnn:
> AttributeError: 'NoneType' object has no attribute 'rcnn'
> ```

hello,
i have the same question.do you solve this problem?
looking forward to your reply

**Comment by Superfly12138** [comment]
> > 当我测试训练有素的模块时，我输入此命令
> > ```
> > python tools/test.py configs/faster_rcnn_r50_augfpn_1x.py epoch_8.pth --gpus 4 --out results.pkl --eval bbox
> > ```
> > 
> > 
> > 但发生错误：
> > NoneType'对象没有属性'rcnn'
> > 细节：
> > ```
> > File "tools/test.py", line 127, in <module>
> >     main()
> >   File "tools/test.py", line 78, in main
> >     cfg.model, train_cfg=None, test_cfg=cfg.test_cfg)
> >   File "/home/superfly/AugFPN-master/mmdet/models/builder.py", line 51, in build_detector
> >     return build(cfg, DETECTORS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
> >   File "/home/superfly/AugFPN-master/mmdet/models/builder.py", line 31, in build
> >     return _build_module(cfg, registry, default_args)
> >   File "/home/superfly/AugFPN-master/mmdet/models/builder.py", line 23, in _build_module
> >     return obj_type(**args)
> >   File "/home/superfly/AugFPN-master/mmdet/models/detectors/faster_rcnn.py", line 25, in __init__
> >     pretrained=pretrained)
> >   File "/home/superfly/AugFPN-master/mmdet/models/detectors/two_stage.py", line 44, in __init__
> >     if 'use_consistent_supervision' in self.train_cfg.rcnn:
> > AttributeError: 'NoneType' object has no attribute 'rcnn'
> > ```
> 
> hello,
> i have the same question.do you solve this problem?
> looking forward to your reply

sorry,didn't solve yet

**Comment by Gus-Guo** [comment]
Sorry about that. Fixed that already.
